# Netlify configuration for the frontend application

[build]
  base    = "frontend"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs" # Essential plugin for Next.js sites on Netlify