# Netlify configuration for the frontend application

[build]
  base    = "frontend"      # Netlify will run the build command in this directory
  command = "npm run build" # The command to build your Next.js app
  publish = "frontend/.next"  # The directory that contains the built site

[[plugins]]
  package = "@netlify/plugin-nextjs" # Essential plugin for Next.js sites on Netlify